vlib work
vcom  overflow_detection.vhd
vcom  saturation_out.vhd
vcom  Overflow_Detection_and_Saturation_4_bit_adder.vhd
vcom  Overflow_Detection_and_Saturation_4_bit_adder_tb_pkg.vhd
vcom  Overflow_Detection_and_Saturation_4_bit_adder_tb.vhd
