-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\CodeGeneration\Delay.vhd
-- Created: 2018-10-16 03:29:30
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Delay
-- Source Path: CodeGeneration/Delay
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Delay IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(4 DOWNTO 0);  -- sfix5_En2
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(4 DOWNTO 0)  -- sfix5_En2
        );
END Delay;


ARCHITECTURE rtl OF Delay IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_signed                       : signed(4 DOWNTO 0);  -- sfix5_En2
  SIGNAL Delay_out1                       : signed(4 DOWNTO 0);  -- sfix5_En2

BEGIN
  In1_signed <= signed(In1);

  enb <= clk_enable;

  -- <S1>/Delay
  Delay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= In1_signed;
      END IF;
    END IF;
  END PROCESS Delay_1_process;


  Out1 <= std_logic_vector(Delay_out1);

  ce_out <= clk_enable;

END rtl;

