-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\SelectorAdder\Subsystem_tb.vhd
-- Created: 2018-10-16 04:24:57
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
USE work.Subsystem_tb_pkg.ALL;

ENTITY Subsystem_tb IS
END Subsystem_tb;


ARCHITECTURE rtl OF Subsystem_tb IS

  -- Component Declarations
  COMPONENT Subsystem
    PORT( In1                             :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          In2                             :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2_En1
          In3                             :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          In4                             :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          In5                             :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          Out1                            :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem
    USE ENTITY work.Subsystem(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL Out1_done                        : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL Out1_done_enb                    : std_logic;  -- ufix1
  SIGNAL Out1_addr                        : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Out1_active                      : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL Out1_enb                         : std_logic;  -- ufix1
  SIGNAL Out1_lastAddr                    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion_out1_addr   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Data_Type_Conversion_out1_active : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion_out1_enb    : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion_out1_addr_delay_1 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL rawData_In1                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL holdData_In1                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rawData_In2                      : unsigned(1 DOWNTO 0);  -- ufix2_En1
  SIGNAL holdData_In2                     : unsigned(1 DOWNTO 0);  -- ufix2_En1
  SIGNAL rawData_In3                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL holdData_In3                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rawData_In4                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL holdData_In4                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rawData_In5                      : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL holdData_In5                     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In1_offset                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In1                              : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In1_1                            : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL In2_offset                       : unsigned(1 DOWNTO 0);  -- ufix2_En1
  SIGNAL In2_1                            : unsigned(1 DOWNTO 0);  -- ufix2_En1
  SIGNAL In2_2                            : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL In3_offset                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In3_1                            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In3_2                            : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL In4_offset                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In4_1                            : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In4_2                            : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL In5_offset                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In5_1                            : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In5_2                            : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL Out1                             : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL Out1_unsigned                    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Out1_addr_delay_1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Out1_expected                    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Out1_ref                         : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Out1_testFailure                 : std_logic;  -- ufix1

BEGIN
  u_Subsystem : Subsystem
    PORT MAP( In1 => In1_1,  -- ufix2
              In2 => In2_2,  -- ufix2_En1
              In3 => In3_2,  -- ufix2
              In4 => In4_2,  -- ufix2
              In5 => In5_2,  -- ufix3
              Out1 => Out1  -- ufix3
              );

  Out1_done_enb <= Out1_done AND rdEnb;

  
  Out1_active <= '1' WHEN Out1_addr /= to_unsigned(16#A#, 4) ELSE
      '0';

  enb <= rdEnb AFTER 2 ns;

  snkDonen <=  NOT check1_done;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF check1_done = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'event AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;

  
  rdEnb <= tb_enb_delay WHEN check1_done = '0' ELSE
      '0';

  ce_out <= enb AND (rdEnb AND tb_enb_delay);

  Out1_enb <= ce_out AND Out1_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 10
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_addr <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Out1_enb = '1' THEN
        IF Out1_addr = to_unsigned(16#A#, 4) THEN 
          Out1_addr <= to_unsigned(16#0#, 4);
        ELSE 
          Out1_addr <= Out1_addr + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  Out1_lastAddr <= '1' WHEN Out1_addr >= to_unsigned(16#A#, 4) ELSE
      '0';

  Out1_done <= Out1_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF Out1_done_enb = '1' THEN
        check1_done <= Out1_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  
  Data_Type_Conversion_out1_active <= '1' WHEN Data_Type_Conversion_out1_addr /= to_unsigned(16#A#, 4) ELSE
      '0';

  Data_Type_Conversion_out1_enb <= Data_Type_Conversion_out1_active AND (rdEnb AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 10
  DataTypeConversion_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Data_Type_Conversion_out1_addr <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Data_Type_Conversion_out1_enb = '1' THEN
        IF Data_Type_Conversion_out1_addr = to_unsigned(16#A#, 4) THEN 
          Data_Type_Conversion_out1_addr <= to_unsigned(16#0#, 4);
        ELSE 
          Data_Type_Conversion_out1_addr <= Data_Type_Conversion_out1_addr + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS DataTypeConversion_process;


  Data_Type_Conversion_out1_addr_delay_1 <= Data_Type_Conversion_out1_addr AFTER 1 ns;

  -- Data source for In1
  In1_fileread: PROCESS (Data_Type_Conversion_out1_addr_delay_1, tb_enb_delay, rdEnb)
    FILE fp: TEXT open READ_MODE is "In1.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(3 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    rawData_In1 <= unsigned(read_data(1 DOWNTO 0));
  END PROCESS In1_fileread;

  -- holdData reg for Data_Type_Conversion_out1
  stimuli_Data_Type_Conversion_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In1 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In1 <= rawData_In1;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion_out1_process;

  -- Data source for In2
  rawData_In2 <= to_unsigned(16#2#, 2);

  -- holdData reg for Data_Type_Conversion1_out1
  stimuli_Data_Type_Conversion1_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In2 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In2 <= rawData_In2;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion1_out1_process;

  -- Data source for In3
  rawData_In3 <= to_unsigned(16#2#, 2);

  -- holdData reg for Data_Type_Conversion2_out1
  stimuli_Data_Type_Conversion2_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In3 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In3 <= rawData_In3;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion2_out1_process;

  -- Data source for In4
  rawData_In4 <= to_unsigned(16#3#, 2);

  -- holdData reg for Data_Type_Conversion3_out1
  stimuli_Data_Type_Conversion3_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In4 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In4 <= rawData_In4;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion3_out1_process;

  -- Data source for In5
  rawData_In5 <= to_unsigned(16#4#, 3);

  -- holdData reg for Data_Type_Conversion4_out1
  stimuli_Data_Type_Conversion4_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In5 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In5 <= rawData_In5;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion4_out1_process;

  stimuli_Data_Type_Conversion_out1_1: PROCESS (rawData_In1, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In1_offset <= holdData_In1;
    ELSE
      In1_offset <= rawData_In1;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion_out1_1;

  In1 <= In1_offset AFTER 2 ns;

  In1_1 <= std_logic_vector(In1);

  stimuli_Data_Type_Conversion1_out1_1: PROCESS (rawData_In2, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In2_offset <= holdData_In2;
    ELSE
      In2_offset <= rawData_In2;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion1_out1_1;

  In2_1 <= In2_offset AFTER 2 ns;

  In2_2 <= std_logic_vector(In2_1);

  stimuli_Data_Type_Conversion2_out1_1: PROCESS (rawData_In3, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In3_offset <= holdData_In3;
    ELSE
      In3_offset <= rawData_In3;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion2_out1_1;

  In3_1 <= In3_offset AFTER 2 ns;

  In3_2 <= std_logic_vector(In3_1);

  stimuli_Data_Type_Conversion3_out1_1: PROCESS (rawData_In4, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In4_offset <= holdData_In4;
    ELSE
      In4_offset <= rawData_In4;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion3_out1_1;

  In4_1 <= In4_offset AFTER 2 ns;

  In4_2 <= std_logic_vector(In4_1);

  stimuli_Data_Type_Conversion4_out1_1: PROCESS (rawData_In5, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In5_offset <= holdData_In5;
    ELSE
      In5_offset <= rawData_In5;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion4_out1_1;

  In5_1 <= In5_offset AFTER 2 ns;

  In5_2 <= std_logic_vector(In5_1);

  Out1_unsigned <= unsigned(Out1);

  Out1_addr_delay_1 <= Out1_addr AFTER 1 ns;

  -- Data source for Out1_expected
  Out1_expected_fileread: PROCESS (Out1_addr_delay_1, tb_enb_delay, rdEnb)
    FILE fp: TEXT open READ_MODE is "Out1_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(3 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    Out1_expected <= unsigned(read_data(2 DOWNTO 0));
  END PROCESS Out1_expected_fileread;

  Out1_ref <= Out1_expected;

  Out1_unsigned_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND Out1_unsigned /= Out1_ref THEN
        Out1_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in Out1_unsigned: Expected " & to_hex(Out1_ref) & (" Actual " & to_hex(Out1_unsigned))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS Out1_unsigned_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF check1_done = '1' THEN
        IF Out1_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

