vlib work
vcom  Phase_Sel.vhd
vcom  Shift_Sel.vhd
vcom  Shift_Sel1.vhd
vcom  Stage_0.vhd
vcom  Phase_Sel_block.vhd
vcom  Shift_Sel_block.vhd
vcom  Shift_Sel1_block.vhd
vcom  Stage_1.vhd
vcom  Phase_Sel_block1.vhd
vcom  Shift_Sel_block1.vhd
vcom  Shift_Sel1_block1.vhd
vcom  Stage_10.vhd
vcom  Phase_Sel_block2.vhd
vcom  Shift_Sel_block2.vhd
vcom  Shift_Sel1_block2.vhd
vcom  Stage_11.vhd
vcom  Phase_Sel_block3.vhd
vcom  Shift_Sel_block3.vhd
vcom  Shift_Sel1_block3.vhd
vcom  Stage_2.vhd
vcom  Phase_Sel_block4.vhd
vcom  Shift_Sel_block4.vhd
vcom  Shift_Sel1_block4.vhd
vcom  Stage_3.vhd
vcom  Phase_Sel_block5.vhd
vcom  Shift_Sel_block5.vhd
vcom  Shift_Sel1_block5.vhd
vcom  Stage_4.vhd
vcom  Phase_Sel_block6.vhd
vcom  Shift_Sel_block6.vhd
vcom  Shift_Sel1_block6.vhd
vcom  Stage_5.vhd
vcom  Phase_Sel_block7.vhd
vcom  Shift_Sel_block7.vhd
vcom  Shift_Sel1_block7.vhd
vcom  Stage_6.vhd
vcom  Phase_Sel_block8.vhd
vcom  Shift_Sel_block8.vhd
vcom  Shift_Sel1_block8.vhd
vcom  Stage_7.vhd
vcom  Phase_Sel_block9.vhd
vcom  Shift_Sel_block9.vhd
vcom  Shift_Sel1_block9.vhd
vcom  Stage_8.vhd
vcom  Phase_Sel_block10.vhd
vcom  Shift_Sel_block10.vhd
vcom  Shift_Sel1_block10.vhd
vcom  Stage_9.vhd
vcom  CORDIC_cos_sin.vhd
vcom  CORDIC_cos_sin_tb_pkg.vhd
vcom  CORDIC_cos_sin_tb.vhd
