-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\CORDIC\Phase_Sel_block10.vhd
-- Created: 2018-11-13 04:29:10
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Phase_Sel_block10
-- Source Path: CORDIC/CORDIC_cos_sin/Stage_9/Phase_Sel
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Phase_Sel_block10 IS
  PORT( sel                               :   IN    std_logic;
        out_rsvd                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END Phase_Sel_block10;


ARCHITECTURE rtl OF Phase_Sel_block10 IS

  -- Signals
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Unary_Minus_cast                 : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL Unary_Minus_cast_1               : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL Unary_Minus_out1                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Multiport_Switch_out1            : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  -- <S91>/Constant
  Constant_out1 <= to_signed(16#0040#, 16);

  -- <S91>/Unary Minus
  Unary_Minus_cast <= resize(Constant_out1, 17);
  Unary_Minus_cast_1 <=  - (Unary_Minus_cast);
  Unary_Minus_out1 <= Unary_Minus_cast_1(15 DOWNTO 0);

  -- <S91>/Multiport Switch
  
  Multiport_Switch_out1 <= Unary_Minus_out1 WHEN sel = '0' ELSE
      Constant_out1;

  out_rsvd <= std_logic_vector(Multiport_Switch_out1);

END rtl;

