-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\TapFilter\Fixed.vhd
-- Created: 2018-10-21 10:40:11
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Fixed
-- Source Path: TapFilter/Fixed
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Fixed IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10_En6
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10_En6
        );
END Fixed;


ARCHITECTURE rtl OF Fixed IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_signed                       : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Gain_mul_temp                    : signed(12 DOWNTO 0);  -- sfix13_En7
  SIGNAL Gain_cast                        : signed(11 DOWNTO 0);  -- sfix12_En7
  SIGNAL Gain_out1                        : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Delay_out1                       : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Gain1_mul_temp                   : signed(12 DOWNTO 0);  -- sfix13_En8
  SIGNAL Gain1_out1                       : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Add_add_cast                     : signed(31 DOWNTO 0);  -- sfix32_En6
  SIGNAL Add_add_cast_1                   : signed(31 DOWNTO 0);  -- sfix32_En6
  SIGNAL Add_add_temp                     : signed(31 DOWNTO 0);  -- sfix32_En6
  SIGNAL Add_out1                         : signed(9 DOWNTO 0);  -- sfix10_En6

BEGIN
  In1_signed <= signed(In1);

  enb <= clk_enable;

  -- <S1>/Gain
  Gain_mul_temp <= to_signed(16#3#, 3) * In1_signed;
  Gain_cast <= Gain_mul_temp(11 DOWNTO 0);
  Gain_out1 <= Gain_cast(10 DOWNTO 1);

  -- <S1>/Delay
  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(16#000#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= In1_signed;
      END IF;
    END IF;
  END PROCESS Delay_process;


  -- <S1>/Gain1
  Gain1_mul_temp <= to_signed(-16#1#, 3) * Delay_out1;
  Gain1_out1 <= Gain1_mul_temp(11 DOWNTO 2);

  -- <S1>/Add
  Add_add_cast <= resize(Gain_out1, 32);
  Add_add_cast_1 <= resize(Gain1_out1, 32);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  Add_out1 <= Add_add_temp(9 DOWNTO 0);

  Out1 <= std_logic_vector(Add_out1);

  ce_out <= clk_enable;

END rtl;