-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Selector\Subsystem.vhd
-- Created: 2018-10-16 04:19:29
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: Selector/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( In1                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        In2                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2_En1
        In3                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        In4                               :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        In5                               :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        Out1                              :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Constant4_out1                   : unsigned(1 DOWNTO 0);  -- ufix2_En1
  SIGNAL Add_add_cast                     : unsigned(31 DOWNTO 0);  -- ufix32_En1
  SIGNAL Add_add_cast_1                   : unsigned(31 DOWNTO 0);  -- ufix32_En1
  SIGNAL Add_add_temp                     : unsigned(31 DOWNTO 0);  -- ufix32_En1
  SIGNAL Add_out1                         : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In2_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2_En1
  SIGNAL In2_dtc                          : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In3_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In3_dtc                          : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In4_unsigned                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL In4_dtc                          : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL In5_unsigned                     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Multiport_Switch_out1            : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  In1_unsigned <= unsigned(In1);

  -- <S1>/Constant4
  -- 
  -- <S1>/Data Type Conversion
  Constant4_out1 <= to_unsigned(16#2#, 2);

  -- <S1>/Add
  Add_add_cast <= resize(In1_unsigned & '0', 32);
  Add_add_cast_1 <= resize(Constant4_out1, 32);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  Add_out1 <= Add_add_temp(3 DOWNTO 1);

  In2_unsigned <= unsigned(In2);

  In2_dtc <= resize(unsigned'('0' & In2_unsigned(1)), 3);

  In3_unsigned <= unsigned(In3);

  In3_dtc <= resize(In3_unsigned, 3);

  In4_unsigned <= unsigned(In4);

  In4_dtc <= resize(In4_unsigned, 3);

  In5_unsigned <= unsigned(In5);

  -- <S1>/Multiport Switch
  
  Multiport_Switch_out1 <= In2_dtc WHEN Add_out1 = to_unsigned(16#1#, 3) ELSE
      In3_dtc WHEN Add_out1 = to_unsigned(16#2#, 3) ELSE
      In4_dtc WHEN Add_out1 = to_unsigned(16#3#, 3) ELSE
      In5_unsigned;

  Out1 <= std_logic_vector(Multiport_Switch_out1);

END rtl;

