-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\TapFilter\Fixed_tb.vhd
-- Created: 2018-10-21 10:49:34
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Fixed_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Fixed_tb_pkg.ALL;

ENTITY Fixed_tb IS
END Fixed_tb;


ARCHITECTURE rtl OF Fixed_tb IS

  -- Component Declarations
  COMPONENT Fixed
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          In1                             :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10_En6
          ce_out                          :   OUT   std_logic;
          Out1                            :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10_En6
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Fixed
    USE ENTITY work.Fixed(rtl);

  -- Constants
  CONSTANT In1_table_data                 : vector_of_std_logic_vector10(0 TO 100) := 
    ("0001001010",
     "0000101000",
     "0000000100",
     "0000010110",
     "1111010011",
     "0001101100",
     "0000000011",
     "0001110011",
     "0000010000",
     "0000110111",
     "1110100011",
     "1111010011",
     "0001001111",
     "1111010111",
     "0000100100",
     "1111101000",
     "1111110111",
     "1110101001",
     "1110101110",
     "0000111111",
     "1111111101",
     "1111001100",
     "1111001111",
     "0000110111",
     "1111111100",
     "0000100000",
     "0000011001",
     "0000110000",
     "0000011001",
     "1110101010",
     "0000011000",
     "0001001000",
     "0000101110",
     "1101100111",
     "1111101110",
     "1111101011",
     "0000010100",
     "1111011111",
     "1111111111",
     "0001100110",
     "0000110110",
     "0000010001",
     "1111000100",
     "1111111011",
     "0000001001",
     "1111011100",
     "1111101010",
     "0000011010",
     "0001100011",
     "1101100011",
     "1110111001",
     "0001000111",
     "0000100101",
     "1111101110",
     "0000011010",
     "1111000001",
     "1110111110",
     "0000010100",
     "0001100001",
     "0000101111",
     "1111011111",
     "0000111000",
     "1111110000",
     "1111010001",
     "1111100011",
     "1111011000",
     "1111110010",
     "0000100011",
     "1110111011",
     "0000010110",
     "0001001000",
     "0000001001",
     "0000101101",
     "1111111100",
     "0010000001",
     "0000111011",
     "1110001011",
     "0000000010",
     "1110001100",
     "0001000001",
     "0000011001",
     "0000101000",
     "0000110111",
     "0001110000",
     "1111101011",
     "1111110111",
     "0000100111",
     "0000111110",
     "1110111000",
     "1111011100",
     "0000000010",
     "1101100001",
     "0001001010",
     "1110111110",
     "0001001001",
     "1111001101",
     "0000101000",
     "0000110100",
     "1111110100",
     "0000100011",
     "1111110111");  -- ufix10 [101]
  CONSTANT Out1_expected_table_data       : vector_of_std_logic_vector10(0 TO 100) := 
    ("0001101111",
     "0000101001",
     "1111111100",
     "0000100000",
     "1110110110",
     "0010101101",
     "1111101001",
     "0010101011",
     "1111111011",
     "0001001110",
     "1101100110",
     "1111010011",
     "0010000001",
     "1110101110",
     "0001000000",
     "1111010011",
     "1111111000",
     "1101111111",
     "1110011010",
     "0001110010",
     "1111101011",
     "1110110010",
     "1111000011",
     "0001011110",
     "1111101100",
     "0000110001",
     "0000011101",
     "0001000001",
     "0000011001",
     "1101111000",
     "0000111001",
     "0001100110",
     "0000110011",
     "1100001110",
     "0000001011",
     "1111100100",
     "0000100011",
     "1111001001",
     "0000000110",
     "0010011001",
     "0000110111",
     "0000001011",
     "1110100001",
     "0000000111",
     "0000001110",
     "1111000111",
     "1111101000",
     "0000101100",
     "0010001101",
     "1011111011",
     "1110111100",
     "0001111011",
     "0000100101",
     "1111011011",
     "0000101011",
     "1110011010",
     "1110101100",
     "0000101110",
     "0010001100",
     "0000101101",
     "1111000010",
     "0001011100",
     "1111011010",
     "1110111101",
     "1111011111",
     "1111001011",
     "1111110101",
     "0000110111",
     "1110001111",
     "0000110010",
     "0001100110",
     "1111111011",
     "0001000000",
     "1111101110",
     "0011000010",
     "0000110111",
     "1101000001",
     "0000100000",
     "1101010001",
     "0001111110",
     "0000010100",
     "0000110101",
     "0001001000",
     "0010011010",
     "1111000100",
     "1111110111",
     "0000111100",
     "0001010011",
     "1110000100",
     "1111011100",
     "0000001100",
     "1100010000",
     "0010010110",
     "1110001010",
     "0001111101",
     "1110100000",
     "0001001000",
     "0001000100",
     "1111100001",
     "0000110111",
     "1111101001");  -- ufix10 [101]

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL Out1_done                        : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL Out1_done_enb                    : std_logic;  -- ufix1
  SIGNAL Out1_addr                        : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Out1_active                      : std_logic;  -- ufix1
  SIGNAL Data_Type_Conversion_out1_addr   : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Data_Type_Conversion_out1_active : std_logic;  -- ufix1
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL Data_Type_Conversion_out1_enb    : std_logic;  -- ufix1
  SIGNAL In1_1                            : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL rawData_In1                      : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL holdData_In1                     : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL In1_offset                       : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL In1_2                            : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL In1_3                            : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL Out1                             : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL Out1_enb                         : std_logic;  -- ufix1
  SIGNAL Out1_lastAddr                    : std_logic;  -- ufix1
  SIGNAL Out1_signed                      : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Out1_expected_1                  : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL Out1_expected_2                  : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Out1_ref                         : signed(9 DOWNTO 0);  -- sfix10_En6
  SIGNAL Out1_testFailure                 : std_logic;  -- ufix1

BEGIN
  u_Fixed : Fixed
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              In1 => In1_3,  -- sfix10_En6
              ce_out => ce_out,
              Out1 => Out1  -- sfix10_En6
              );

  Out1_done_enb <= Out1_done AND rdEnb;

  
  Out1_active <= '1' WHEN Out1_addr /= to_unsigned(16#64#, 7) ELSE
      '0';

  
  Data_Type_Conversion_out1_active <= '1' WHEN Data_Type_Conversion_out1_addr /= to_unsigned(16#64#, 7) ELSE
      '0';

  Data_Type_Conversion_out1_enb <= Data_Type_Conversion_out1_active AND (rdEnb AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 100
  DataTypeConversion_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Data_Type_Conversion_out1_addr <= to_unsigned(16#00#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Data_Type_Conversion_out1_enb = '1' THEN
        IF Data_Type_Conversion_out1_addr = to_unsigned(16#64#, 7) THEN 
          Data_Type_Conversion_out1_addr <= to_unsigned(16#00#, 7);
        ELSE 
          Data_Type_Conversion_out1_addr <= Data_Type_Conversion_out1_addr + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS DataTypeConversion_process;


  -- Data source for In1
  In1_1 <= In1_table_data(to_integer(Data_Type_Conversion_out1_addr));

  rawData_In1 <= signed(In1_1);

  -- holdData reg for Data_Type_Conversion_out1
  stimuli_Data_Type_Conversion_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In1 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In1 <= rawData_In1;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion_out1_process;

  stimuli_Data_Type_Conversion_out1_1: PROCESS (rawData_In1, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      In1_offset <= holdData_In1;
    ELSE
      In1_offset <= rawData_In1;
    END IF;
  END PROCESS stimuli_Data_Type_Conversion_out1_1;

  In1_2 <= In1_offset AFTER 2 ns;

  In1_3 <= std_logic_vector(In1_2);

  snkDonen <=  NOT check1_done;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'event AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;

  
  rdEnb <= tb_enb_delay WHEN check1_done = '0' ELSE
      '0';

  clk_enable <= rdEnb AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF check1_done = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  Out1_enb <= ce_out AND Out1_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 100
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_addr <= to_unsigned(16#00#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Out1_enb = '1' THEN
        IF Out1_addr = to_unsigned(16#64#, 7) THEN 
          Out1_addr <= to_unsigned(16#00#, 7);
        ELSE 
          Out1_addr <= Out1_addr + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  Out1_lastAddr <= '1' WHEN Out1_addr >= to_unsigned(16#64#, 7) ELSE
      '0';

  Out1_done <= Out1_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF Out1_done_enb = '1' THEN
        check1_done <= Out1_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  Out1_signed <= signed(Out1);

  -- Data source for Out1_expected
  Out1_expected_1 <= Out1_expected_table_data(to_integer(Out1_addr));

  Out1_expected_2 <= signed(Out1_expected_1);

  Out1_ref <= Out1_expected_2;

  Out1_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND Out1_signed /= Out1_ref THEN
        Out1_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in Out1_signed: Expected " & to_hex(Out1_ref) & (" Actual " & to_hex(Out1_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS Out1_signed_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF check1_done = '1' THEN
        IF Out1_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

