function RTW_SidParentMap() {
    this.sidParentMap = new Array();
    this.sidParentMap["overflow_and_saturation:56"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:57"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:33"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:36"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:31"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:35"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:58"] = "overflow_and_saturation:55";
    this.sidParentMap["overflow_and_saturation:31:1"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:3"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:4"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:5"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:6"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:8"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:9"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:10"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:11"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:13"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:15"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:16"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:17"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:19"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:20"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:21"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:23"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:24"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:25"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:31:1:27"] = "overflow_and_saturation:31";
    this.sidParentMap["overflow_and_saturation:35:1"] = "overflow_and_saturation:35";
    this.sidParentMap["overflow_and_saturation:35:1:3"] = "overflow_and_saturation:35";
    this.sidParentMap["overflow_and_saturation:35:1:4"] = "overflow_and_saturation:35";
    this.sidParentMap["overflow_and_saturation:35:1:6"] = "overflow_and_saturation:35";
    this.sidParentMap["overflow_and_saturation:35:1:8"] = "overflow_and_saturation:35";
    this.sidParentMap["overflow_and_saturation:35:1:10"] = "overflow_and_saturation:35";
    this.sidParentMap["overflow_and_saturation:35:1:13"] = "overflow_and_saturation:35";
    this.getParentSid = function(sid) { return this.sidParentMap[sid];}
}
    RTW_SidParentMap.instance = new RTW_SidParentMap();
